### ISSUE TITLE
Error in code & changing the Title of the page?

### ISSUE THREAD

**Issue by netikseo** [vneri/circleDonutChart#3]
You have an error in the code. Line 90:
`		window.requestAnimationFrame = requestAnimationFram;e`

Also why the heck you are changing title of the page on line 237?
`		document.title = "Top "+top+ "   Left "+left;`

Will it work if I uncomment this line? It's very poor experience and will ruin your SEO if you are going to use this library without changing the above line.

**Comment by vneri** [comment]
Thank you, let me check this, seems like two needless errors
Cheers
