### ISSUE TITLE
Start Location of Outer Circle is weird

### ISSUE THREAD

**Issue by aberezovsky** [vneri/circleDonutChart#4]
It's not intuitive for the start location of the outer circle to be at 3 o'clock. Is it possible to change it so it starts at 12 o'clock?

**Comment by vneri** [comment]
> 
> 
> It's not intuitive for the start location of the outer circle to be at 3 o'clock. Is it possible to change it so it starts at 12 o'clock?

Hi there, please check the new release, that supports an option to change the start. I am not changing the standard behaviour for backwards compatibility. Please test it - thank you for your feedback
